### PR TITLE
Add PowerVS IPI scripts folder and a script to extract cloud credentials

### PR DESCRIPTION
**Pull request by AshwinHIBM**
CCOctl.sh retrieves the CCOctl binary, generates credential requests and obtains cloud credentials.

### CODE REVIEW

**Review by yussufsh — APPROVED** [review]
lgtm for v1

**Comment by yussufsh** [comment]
@AshwinHIBM please sign your commit.

**Review by yussufsh — APPROVED** [review]
lgtm

**Comment by yussufsh** [comment]
Please try to add some docs on howto whenever you can.

**Comment by clnperez** [comment]
@alishaIBM @AshwinHIBM did this ever get added to any documentation? you could edit your developer exchange blog post to include it @AshwinHIBM

**Comment by AshwinHIBM** [comment]
> @alishaIBM @AshwinHIBM did this ever get added to any documentation? you could edit your developer exchange blog post to include it @AshwinHIBM

Mike mentioned RedHat doesn't allow such scripts to be included in official documentation but I think I can add this to my blog. There's also https://github.com/ocp-power-automation/ocp4-extras/pull/5 that hasn't merged yet @yussufsh .

**Pull request merged**
