### PR TITLE
Add CCOctl documentation

### PR DESCRIPTION
**Pull request by AshwinHIBM**
Usage information for ccoctl.sh script.

### CODE REVIEW

**Review by yussufsh — DISMISSED** [review]
/lgtm

**Comment by yussufsh** [comment]
@Rajalakshmi-Girish need to enable some plugin for this repo?

**Comment by Rajalakshmi-Girish** [comment]
> @Rajalakshmi-Girish need to enable some plugin for this repo?

I have made changes to plugin for this repo.
@yussufsh Can you try now?

**Review by yussufsh — APPROVED** [review]
/lgtm

**Pull request merged**
